# User
User.create!(:pseudo => "ahe", :firstname => "Anthony", :lastname => "Heukmes", :email => "ahe@ahe.be", :role => "admin")
User.create!(:pseudo => "willd", :firstname => "Wilfried", :lastname => "Dalmat", :email => "willd@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "marcos", :firstname => "Marcos", :lastname => "Camozzato", :email => "marcos@ahe.be", :role => "defender")
User.create!(:pseudo => "onyewuo", :firstname => "Ogushi", :lastname => "Onyewu", :email => "onyewuo@ahe.be", :role => "defender")
User.create!(:pseudo => "sarrm", :firstname => "Momo", :lastname => "Sarr", :email => "sarrm@ahe.be", :role => "defender")
User.create!(:pseudo => "mulemol", :firstname => "Landry", :lastname => "Mulemo", :email => "mulemol@ahe.be", :role => "defender")
User.create!(:pseudo => "witsela", :firstname => "Axel", :lastname => "Witsel", :email => "witsela@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "defours", :firstname => "Steven", :lastname => "Defour", :email => "defours@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "goreuxr", :firstname => "Reginal", :lastname => "Goreux", :email => "goureux@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "jova", :firstname => "Milan", :lastname => "Jovanovic", :email => "jova@ahe.be", :role => "striker")
User.create!(:pseudo => "decamar", :firstname => "Igor", :lastname => "De Camargo", :email => "decamar@ahe.be", :role => "striker")
User.create!(:pseudo => "mbokani", :firstname => "Dieumerci", :lastname => "Mbokani", :email => "mbokani@ahe.be", :role => "striker")
User.create!(:pseudo => "nicaise", :firstname => "Benjamin", :lastname => "Nicaise", :email => "nicaise@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "bolats", :firstname => "Sinan", :lastname => "Bolat", :email => "bolats@ahe.be", :role => "goalkeeper")
User.create!(:pseudo => "leonb", :firstname => "Leon", :lastname => "Benko", :email => "leonb@ahe.be", :role => "striker")
User.create!(:pseudo => "espi", :firstname => "Aragon", :lastname => "Espinoza", :email => "espi@ahe.be", :role => "goalkeeper")
User.create!(:pseudo => "carce", :firstname => "Medhi", :lastname => "Carcela", :email => "carce@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "manga", :firstname => "Eliaquim", :lastname => "Mangala", :email => "manga@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "miku", :firstname => "Tomislav", :lastname => "Mikulic", :email => "miku@ahe.be", :role => "defender")
User.create!(:pseudo => "maestro", :firstname => "Segio", :lastname => "Conceicao", :email => "maestro@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "bolo", :firstname => "Laszlo", :lastname => "Boloni", :email => "bolo@ahe.be", :role => "trainer")
User.create!(:pseudo => "pesto", :firstname => "Joaquim", :lastname => "Preto", :email => "ahe@ahe.be", :role => "trainer")
User.create!(:pseudo => "pf", :firstname => "Pierre", :lastname => "Francois", :email => "pf@ahe.be", :role => "admin")
User.create!(:pseudo => "moi", :firstname => "Moi", :lastname => "Moi", :email => "moi@ahe.be", :role => "striker")

# Pets
Pet.create!(:name => "Youpi", :user_id => 1)
Pet.create!(:name => "Blouk", :user_id => 1)
Pet.create!(:name => "Pif", :user_id => 1)
Pet.create!(:name => "Paf", :user_id => 2)
Pet.create!(:name => "Meuh", :user_id => 3)
Pet.create!(:name => "Boug", :user_id => 3)
Pet.create!(:name => "Zigg", :user_id => 4)
Pet.create!(:name => "Iop", :user_id => 4)
Pet.create!(:name => "Tcham", :user_id => 4)
Pet.create!(:name => "Outch", :user_id => 5)
Pet.create!(:name => "Tzii", :user_id => 5)
Pet.create!(:name => "Tutu", :user_id => 6)
Pet.create!(:name => "Tata", :user_id => 7)
Pet.create!(:name => "Bobo", :user_id => 7)
Pet.create!(:name => "Bulk", :user_id => 7)
Pet.create!(:name => "Rocky", :user_id => 7)
Pet.create!(:name => "Arnold", :user_id => 8)
Pet.create!(:name => "Miii", :user_id => 9)
Pet.create!(:name => "Tititi", :user_id => 10)
Pet.create!(:name => "Bob", :user_id => 11)
Pet.create!(:name => "Max", :user_id => 12)
Pet.create!(:name => "Poop", :user_id => 12)
Pet.create!(:name => "Bikk", :user_id => 13)
Pet.create!(:name => "Allo", :user_id => 13) 

# Player
Player.create!(:pseudo => "ahe", :firstname => "Anthony", :lastname => "Heukmes", :email => "ahe@ahe.be", :role => "admin")
Player.create!(:pseudo => "willd", :firstname => "Wilfried", :lastname => "Dalmat", :email => "willd@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "marcos", :firstname => "Marcos", :lastname => "Camozzato", :email => "marcos@ahe.be", :role => "defender")
Player.create!(:pseudo => "onyewuo", :firstname => "Ogushi", :lastname => "Onyewu", :email => "onyewuo@ahe.be", :role => "defender")
Player.create!(:pseudo => "sarrm", :firstname => "Momo", :lastname => "Sarr", :email => "sarrm@ahe.be", :role => "defender")
Player.create!(:pseudo => "mulemol", :firstname => "Landry", :lastname => "Mulemo", :email => "mulemol@ahe.be", :role => "defender")
Player.create!(:pseudo => "witsela", :firstname => "Axel", :lastname => "Witsel", :email => "witsela@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "defours", :firstname => "Steven", :lastname => "Defour", :email => "defours@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "goreuxr", :firstname => "Reginal", :lastname => "Goreux", :email => "goureux@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "jova", :firstname => "Milan", :lastname => "Jovanovic", :email => "jova@ahe.be", :role => "striker")
Player.create!(:pseudo => "decamar", :firstname => "Igor", :lastname => "De Camargo", :email => "decamar@ahe.be", :role => "striker")
Player.create!(:pseudo => "mbokani", :firstname => "Dieumerci", :lastname => "Mbokani", :email => "mbokani@ahe.be", :role => "striker")
Player.create!(:pseudo => "nicaise", :firstname => "Benjamin", :lastname => "Nicaise", :email => "nicaise@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "bolats", :firstname => "Sinan", :lastname => "Bolat", :email => "bolats@ahe.be", :role => "goalkeeper")
Player.create!(:pseudo => "leonb", :firstname => "Leon", :lastname => "Benko", :email => "leonb@ahe.be", :role => "striker")
Player.create!(:pseudo => "espi", :firstname => "Aragon", :lastname => "Espinoza", :email => "espi@ahe.be", :role => "goalkeeper")
Player.create!(:pseudo => "carce", :firstname => "Medhi", :lastname => "Carcela", :email => "carce@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "manga", :firstname => "Eliaquim", :lastname => "Mangala", :email => "manga@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "miku", :firstname => "Tomislav", :lastname => "Mikulic", :email => "miku@ahe.be", :role => "defender")
Player.create!(:pseudo => "maestro", :firstname => "Segio", :lastname => "Conceicao", :email => "maestro@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "bolo", :firstname => "Laszlo", :lastname => "Boloni", :email => "bolo@ahe.be", :role => "trainer")
Player.create!(:pseudo => "pesto", :firstname => "Joaquim", :lastname => "Preto", :email => "ahe@ahe.be", :role => "trainer")
Player.create!(:pseudo => "pf", :firstname => "Pierre", :lastname => "Francois", :email => "pf@ahe.be", :role => "admin")
Player.create!(:pseudo => "moi", :firstname => "Moi", :lastname => "Moi", :email => "moi@ahe.be", :role => "striker")

# Animals
Animal.create!(:name => "Youpi", :player_id => 1)
Animal.create!(:name => "Blouk", :player_id => 1)
Animal.create!(:name => "Pif", :player_id => 1)
Animal.create!(:name => "Paf", :player_id => 2)
Animal.create!(:name => "Meuh", :player_id => 3)
Animal.create!(:name => "Boug", :player_id => 3)
Animal.create!(:name => "Zigg", :player_id => 4)
Animal.create!(:name => "Iop", :player_id => 4)
Animal.create!(:name => "Tcham", :player_id => 4)
Animal.create!(:name => "Outch", :player_id => 5)
Animal.create!(:name => "Tzii", :player_id => 5)
Animal.create!(:name => "Tutu", :player_id => 6)
Animal.create!(:name => "Tata", :player_id => 7)
Animal.create!(:name => "Bobo", :player_id => 7)
Animal.create!(:name => "Bulk", :player_id => 7)
Animal.create!(:name => "Rocky", :player_id => 7)
Animal.create!(:name => "Arnold", :player_id => 8)
Animal.create!(:name => "Miii", :player_id => 9)
Animal.create!(:name => "Tititi", :player_id => 10)
Animal.create!(:name => "Bob", :player_id => 11)
Animal.create!(:name => "Max", :player_id => 12)
Animal.create!(:name => "Poop", :player_id => 12)
Animal.create!(:name => "Bikk", :player_id => 13)
Animal.create!(:name => "Allo", :player_id => 13) 

# Client
Client.create!(:name => "Client 1")
Client.create!(:name => "Client 2")
Client.create!(:name => "Client 3")

# Invheader
Invheader.create!(:invdate => "2007-10-01", :client_id => 1, :amount => "100.00", :tax => "20.00", :total => "120.00", :note => "note 1" )
Invheader.create!(:invdate => "2007-10-03", :client_id => 1, :amount => "200.00", :tax => "40.00", :total => "240.00", :note => "note 2" )
Invheader.create!(:invdate => "2007-10-02", :client_id => 2, :amount => "300.00", :tax => "60.00", :total => "360.00", :note => "note for invoice 3" )
Invheader.create!(:invdate => "2007-10-04", :client_id => 3, :amount => "150.00", :tax => "0.00", :total => "150.00", :note => "no tax" )
Invheader.create!(:invdate => "2007-10-05", :client_id => 3, :amount => "100.00", :tax => "0.00", :total => "100.00", :note => "no tax" )
Invheader.create!(:invdate => "2007-10-05", :client_id => 1, :amount => "50.00", :tax => "10.00", :total => "60.00", :note => nil )
Invheader.create!(:invdate => "2007-10-05", :client_id => 2, :amount => "120.00", :tax => "12.00", :total => "134.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 3, :amount => "200.00", :tax => "0.00", :total => "200.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 1, :amount => "200.00", :tax => "40.00", :total => "240.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 2, :amount => "100.00", :tax => "20.00", :total => "120.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 1, :amount => "600.00", :tax => "120.00", :total => "720.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 2, :amount => "700.00", :tax => "140.00", :total => "840.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 3, :amount => "1000.00", :tax => "0.00", :total => "1000.00", :note => nil )

# Invline
Invline.create!( :invheader_id => 1, :num => 1, :item => "item 1", :qty => "1.00", :unit => "20.00" )
Invline.create!( :invheader_id => 1, :num => 2, :item => "item 2", :qty => "2.00", :unit => "40.00" )
Invline.create!( :invheader_id => 2, :num => 1, :item => "item 1", :qty => "2.00", :unit => "20.00" )
Invline.create!( :invheader_id => 2, :num => 2, :item => "item 2", :qty => "4.00", :unit => "40.00" )
Invline.create!( :invheader_id => 3, :num => 1, :item => "item 3", :qty => "1.00", :unit => "100.00" )
Invline.create!( :invheader_id => 3, :num => 4, :item => "item 4", :qty => "1.00", :unit => "200.00" )
Invline.create!( :invheader_id => 4, :num => 1, :item => "item 1", :qty => "1.00", :unit => "100.00" )
Invline.create!( :invheader_id => 4, :num => 2, :item => "item 2", :qty => "1.00", :unit => "50.00" )
Invline.create!( :invheader_id => 5, :num => 3, :item => "item 3", :qty => "1.00", :unit => "100.00" )
Invline.create!( :invheader_id => 6, :num => 4, :item => "item 4", :qty => "1.00", :unit => "50.00" )
Invline.create!( :invheader_id => 7, :num => 1, :item => "item 5", :qty => "2.00", :unit => "10.00" )
Invline.create!( :invheader_id => 7, :num => 2, :item => "item 1", :qty => "1.00", :unit => "100.00" )
Invline.create!( :invheader_id => 8, :num => 1, :item => "item 3", :qty => "1.00", :unit => "50.00" )
Invline.create!( :invheader_id => 8, :num => 2, :item => "item 2", :qty => "1.00", :unit => "120.00" )
Invline.create!( :invheader_id => 8, :num => 3, :item => "item 3", :qty => "1.00", :unit => "30.00" )
Invline.create!( :invheader_id => 9, :num => 1, :item => "item 6", :qty => "1.00", :unit => "140.00" )
Invline.create!( :invheader_id => 9, :num => 2, :item => "item 3", :qty => "1.00", :unit => "60.00" )
Invline.create!( :invheader_id => 10, :num => 1, :item => "item 5", :qty => "3.00", :unit => "10.00" )
Invline.create!( :invheader_id => 10, :num => 2, :item => "item 4", :qty => "1.00", :unit => "70.00" )
Invline.create!( :invheader_id => 11, :num => 1, :item => "item 1", :qty => "2.00", :unit => "100.00" )
Invline.create!( :invheader_id => 11, :num => 2, :item => "item 2", :qty => "3.00", :unit => "50.00" )
Invline.create!( :invheader_id => 11, :num => 3, :item => "item 3", :qty => "1.00", :unit => "50.00" )
Invline.create!( :invheader_id => 11, :num => 4, :item => "item 4", :qty => "1.00", :unit => "200.00" )
Invline.create!( :invheader_id => 12, :num => 4, :item => "item 4", :qty => "1.00", :unit => "300.00" )
Invline.create!( :invheader_id => 12, :num => 2, :item => "item 2", :qty => "1.00", :unit => "400.00" )
Invline.create!( :invheader_id => 13, :num => 13, :item => "item 13", :qty => "1.00", :unit => "1000.00" )
# Item


# Account
Account.create!(:parent_id => nil, :name => "A1" , :acc_num => 100001, :debit => 11, :credit => 12, :balance => 13, :level => 0, :lft => 1, :rgt => 14 ) 
Account.create!(:parent_id => nil, :name => "A11" , :acc_num => 100011, :debit => 111, :credit => 112, :balance => 113, :level => 1, :lft => 2, :rgt => 3 ) 
Account.create!(:parent_id => nil, :name => "A12" , :acc_num => 100012, :debit => 121, :credit => 122, :balance => 123, :level => 1, :lft => 4, :rgt => 11 ) 
Account.create!(:parent_id => nil, :name => "A13" , :acc_num => 100013, :debit => 131, :credit => 132, :balance => 133, :level => 1, :lft => 12, :rgt => 13 ) 
Account.create!(:parent_id => nil, :name => "A121" , :acc_num => 100121, :debit => 1211, :credit => 1212, :balance => 1213, :level => 2, :lft => 5, :rgt => 8 ) 
Account.create!(:parent_id => nil, :name => "A122" , :acc_num => 100122, :debit => 1221, :credit => 1222, :balance => 1223, :level => 2, :lft => 9, :rgt => 10 ) 
Account.create!(:parent_id => nil, :name => "A1211" , :acc_num => 101211, :debit => 12111, :credit => 12112, :balance => 12113, :level => 3, :lft => 6, :rgt => 7 ) 

# Birds
Bird.create!(:name => "Great <em>Bittern</em>", :scientific_name => "Botaurus stellaris")
Bird.create!(:name => "Little <em>Grebe</em>", :scientific_name => "Tachybaptus ruficollis")
Bird.create!(:name => "Black-necked Grebe", :scientific_name => "Podiceps nigricollis")
Bird.create!(:name => "Little Bittern", :scientific_name => "Ixobrychus minutus")
Bird.create!(:name => "Black-crowned Night Heron", :scientific_name => "Nycticorax nycticorax")
Bird.create!(:name => "Purple Heron", :scientific_name => "Ardea purpurea")
Bird.create!(:name => "White Stork", :scientific_name => "Ciconia ciconia")
Bird.create!(:name => "Spoonbill", :scientific_name => "Platalea leucorodia")
Bird.create!(:name => "Red-crested Pochard", :scientific_name => "Netta rufina")
Bird.create!(:name => "Common Eider", :scientific_name => "Somateria mollissima")
Bird.create!(:name => "Red Kite", :scientific_name => "Milvus milvus")
Bird.create!(:name => "Hen Harrier", :scientific_name => "Circus cyaneus")
Bird.create!(:name => "Montagu`s Harrier", :scientific_name => "Circus pygargus")
Bird.create!(:name => "Black Grouse", :scientific_name => "Tetrao tetrix")
Bird.create!(:name => "Grey Partridge", :scientific_name => "Perdix perdix")
Bird.create!(:name => "Spotted Crake", :scientific_name => "Porzana porzana")
Bird.create!(:name => "Corncrake", :scientific_name => "Crex crex")
Bird.create!(:name => "Common Crane", :scientific_name => "Grus grus")
Bird.create!(:name => "Avocet", :scientific_name => "Recurvirostra avosetta")
Bird.create!(:name => "Stone Curlew", :scientific_name => "Burhinus oedicnemus")
Bird.create!(:name => "Common Ringed Plover", :scientific_name => "Charadrius hiaticula")
Bird.create!(:name => "Kentish Plover", :scientific_name => "Charadrius alexandrinus")
Bird.create!(:name => "Ruff", :scientific_name => "Philomachus pugnax")
Bird.create!(:name => "Common Snipe", :scientific_name => "Gallinago gallinago")
Bird.create!(:name => "Black-tailed Godwit", :scientific_name => "Limosa limosa")
Bird.create!(:name => "Common Redshank", :scientific_name => "Tringa totanus")
Bird.create!(:name => "Sandwich Tern", :scientific_name => "Sterna sandvicensis")
Bird.create!(:name => "Common Tern", :scientific_name => "Sterna hirundo")
Bird.create!(:name => "Arctic Tern", :scientific_name => "Sterna paradisaea")
Bird.create!(:name => "Little Tern", :scientific_name => "Sternula albifrons")
Bird.create!(:name => "Black Tern", :scientific_name => "Chlidonias niger")
Bird.create!(:name => "Barn Owl", :scientific_name => "Tyto alba")
Bird.create!(:name => "Little Owl", :scientific_name => "Athene noctua")
Bird.create!(:name => "Short-eared Owl", :scientific_name => "Asio flammeus")
Bird.create!(:name => "European Nightjar", :scientific_name => "Caprimulgus europaeus")
Bird.create!(:name => "Common Kingfisher", :scientific_name => "Alcedo atthis")
Bird.create!(:name => "Eurasian Hoopoe", :scientific_name => "Upupa epops")
Bird.create!(:name => "Eurasian Wryneck", :scientific_name => "Jynx torquilla")
Bird.create!(:name => "European Green Woodpecker", :scientific_name => "Picus viridis")
Bird.create!(:name => "Crested Lark", :scientific_name => "Galerida cristata")
Bird.create!(:name => "White-headed Duck", :scientific_name => "Oxyura leucocephala")
Bird.create!(:name => "Pale-bellied Brent Goose", :scientific_name => "Branta hrota")
Bird.create!(:name => "Tawny Pipit", :scientific_name => "Anthus campestris")
Bird.create!(:name => "Whinchat", :scientific_name => "Saxicola rubetra")
Bird.create!(:name => "European Stonechat", :scientific_name => "Saxicola rubicola")
Bird.create!(:name => "Northern Wheatear", :scientific_name => "Oenanthe oenanthe")
Bird.create!(:name => "Savi`s Warbler", :scientific_name => "Locustella luscinioides")
Bird.create!(:name => "Sedge Warbler", :scientific_name => "Acrocephalus schoenobaenus")
Bird.create!(:name => "Great Reed Warbler", :scientific_name => "Acrocephalus arundinaceus")
Bird.create!(:name => "Bearded Reedling", :scientific_name => "Panurus biarmicus")
Bird.create!(:name => "Red-backed Shrike", :scientific_name => "Lanius collurio")
Bird.create!(:name => "Great Grey Shrike", :scientific_name => "Lanius excubitor")
Bird.create!(:name => "Woodchat Shrike", :scientific_name => "Lanius senator")
Bird.create!(:name => "Common Raven", :scientific_name => "Corvus corax")
Bird.create!(:name => "Yellowhammer", :scientific_name => "Emberiza citrinella")
Bird.create!(:name => "Ortolan Bunting", :scientific_name => "Emberiza hortulana")
Bird.create!(:name => "Corn Bunting", :scientific_name => "Emberiza calandra")
Bird.create!(:name => "Great Cormorant", :scientific_name => "Phalacrocorax carbo")
Bird.create!(:name => "Hawfinch", :scientific_name => "Coccothraustes coccothraustes")
Bird.create!(:name => "Common Shelduck", :scientific_name => "Tadorna tadorna")
Bird.create!(:name => "Bluethroat", :scientific_name => "Luscinia svecica")
Bird.create!(:name => "Grey Heron", :scientific_name => "Ardea cinerea")
Bird.create!(:name => "Barn Swallow", :scientific_name => "Hirundo rustica")
Bird.create!(:name => "Hooded Crow", :scientific_name => "Corvus cornix")
Bird.create!(:name => "Dunlin", :scientific_name => "Calidris alpina")
Bird.create!(:name => "Eurasian Pied Flycatcher", :scientific_name => "Ficedula hypoleuca")
Bird.create!(:name => "Eurasian Nuthatch", :scientific_name => "Sitta europaea")
Bird.create!(:name => "Short-toed Tree Creeper", :scientific_name => "Certhia brachydactyla")
Bird.create!(:name => "Wood Lark", :scientific_name => "Lullula arborea")
Bird.create!(:name => "Tree Pipit", :scientific_name => "Anthus trivialis")
Bird.create!(:name => "Eurasian Hobby", :scientific_name => "Falco subbuteo")
Bird.create!(:name => "Marsh Warbler", :scientific_name => "Acrocephalus palustris")
Bird.create!(:name => "Wood Sandpiper", :scientific_name => "Tringa glareola")
Bird.create!(:name => "Tawny Owl", :scientific_name => "Strix aluco")
Bird.create!(:name => "Lesser Whitethroat", :scientific_name => "Sylvia curruca")
Bird.create!(:name => "Barnacle Goose", :scientific_name => "Branta leucopsis")
Bird.create!(:name => "Common Goldeneye", :scientific_name => "Bucephala clangula")
Bird.create!(:name => "Western Marsh Harrier", :scientific_name => "Circus aeruginosus")
Bird.create!(:name => "Common Buzzard", :scientific_name => "Buteo buteo")
Bird.create!(:name => "Sanderling", :scientific_name => "Calidris alba")
Bird.create!(:name => "Little Gull", :scientific_name => "Larus minutus")
Bird.create!(:name => "Eurasian Magpie", :scientific_name => "Pica pica")
Bird.create!(:name => "Willow Warbler", :scientific_name => "Phylloscopus trochilus")
Bird.create!(:name => "Wood Warbler", :scientific_name => "Phylloscopus sibilatrix")
Bird.create!(:name => "Great Crested Grebe", :scientific_name => "Podiceps cristatus")
Bird.create!(:name => "Eurasian Jay", :scientific_name => "Garrulus glandarius")
Bird.create!(:name => "Common Redstart", :scientific_name => "Phoenicurus phoenicurus")
Bird.create!(:name => "Blue-headed Wagtail", :scientific_name => "Motacilla flava")
Bird.create!(:name => "Common Swift", :scientific_name => "Apus apus")
Bird.create!(:name => "Marsh Tit", :scientific_name => "Poecile palustris")
Bird.create!(:name => "Goldcrest", :scientific_name => "Regulus regulus")
Bird.create!(:name => "European Golden Plover", :scientific_name => "Pluvialis apricaria")
Bird.create!(:name => "Eurasian Bullfinch", :scientific_name => "Pyrrhula pyrrhula")
Bird.create!(:name => "Common Whitethroat", :scientific_name => "Sylvia communis")
Bird.create!(:name => "Meadow Pipit", :scientific_name => "Anthus pratensis")
Bird.create!(:name => "Greylag Goose", :scientific_name => "Anser anser")
Bird.create!(:name => "Spotted Flycatcher", :scientific_name => "Muscicapa striata")
Bird.create!(:name => "European Greenfinch", :scientific_name => "Carduelis chloris")
Bird.create!(:name => "Common Greenshank", :scientific_name => "Tringa nebularia")
Bird.create!(:name => "Great Spotted Woodpecker", :scientific_name => "Dendrocopos major")
Bird.create!(:name => "Greater Canada Goose", :scientific_name => "Branta canadensis")
Bird.create!(:name => "Mistle Thrush", :scientific_name => "Turdus viscivorus")
Bird.create!(:name => "Great Black-backed Gull", :scientific_name => "Larus marinus")
Bird.create!(:name => "Goosander", :scientific_name => "Mergus merganser")
Bird.create!(:name => "Great Egret", :scientific_name => "Casmerodius albus")
Bird.create!(:name => "Northern Goshawk", :scientific_name => "Accipiter gentilis")
Bird.create!(:name => "Dunnock", :scientific_name => "Prunella modularis")
Bird.create!(:name => "Stock Dove", :scientific_name => "Columba oenas")
Bird.create!(:name => "Common Wood Pigeon", :scientific_name => "Columba palumbus")
Bird.create!(:name => "Eurasian Woodcock", :scientific_name => "Scolopax rusticola")
Bird.create!(:name => "House Sparrow", :scientific_name => "Passer domesticus")
Bird.create!(:name => "Common House Martin", :scientific_name => "Delichon urbicum")
Bird.create!(:name => "Red Knot", :scientific_name => "Calidris canutus")
Bird.create!(:name => "Western Jackdaw", :scientific_name => "Corvus monedula")
Bird.create!(:name => "Brambling", :scientific_name => "Fringilla montifringilla")
Bird.create!(:name => "Northern Lapwing", :scientific_name => "Vanellus vanellus")
Bird.create!(:name => "European Reed Warbler", :scientific_name => "Acrocephalus scirpaceus")
Bird.create!(:name => "Lesser Black-backed Gull", :scientific_name => "Larus fuscus")
Bird.create!(:name => "Little Egret", :scientific_name => "Egretta garzetta")
Bird.create!(:name => "Little Stint", :scientific_name => "Calidris minuta")
Bird.create!(:name => "Common Linnet", :scientific_name => "Carduelis cannabina")
Bird.create!(:name => "Mute Swan", :scientific_name => "Cygnus olor")
Bird.create!(:name => "Common Cuckoo", :scientific_name => "Cuculus canorus")
Bird.create!(:name => "Black-headed Gull", :scientific_name => "Larus ridibundus")
Bird.create!(:name => "Greater White-fronted Goose", :scientific_name => "Anser albifrons")
Bird.create!(:name => "Great Tit", :scientific_name => "Parus major")
Bird.create!(:name => "Redwing", :scientific_name => "Turdus iliacus")
Bird.create!(:name => "Gadwall", :scientific_name => "Anas strepera")
Bird.create!(:name => "Fieldfare", :scientific_name => "Turdus pilaris")
Bird.create!(:name => "Tufted Duck", :scientific_name => "Aythya fuligula")
Bird.create!(:name => "Crested Tit", :scientific_name => "Lophophanes cristatus")
Bird.create!(:name => "Willow Tit", :scientific_name => "Poecile montanus")
Bird.create!(:name => "Eurasian Coot", :scientific_name => "Fulica atra")
Bird.create!(:name => "Common Blackbird", :scientific_name => "Turdus merula")
Bird.create!(:name => "Smew", :scientific_name => "Mergus albellus")
Bird.create!(:name => "Common Sandpiper", :scientific_name => "Actitis hypoleucos")
Bird.create!(:name => "Sand Martin", :scientific_name => "Riparia riparia")
Bird.create!(:name => "Purple Sandpiper", :scientific_name => "Calidris maritima")
Bird.create!(:name => "Northern Pintail", :scientific_name => "Anas acuta")
Bird.create!(:name => "Blue Tit", :scientific_name => "Cyanistes caeruleus")
Bird.create!(:name => "European Goldfinch", :scientific_name => "Carduelis carduelis")
Bird.create!(:name => "Eurasian Whimbrel", :scientific_name => "Numenius phaeopus")
Bird.create!(:name => "Common Reed Bunting", :scientific_name => "Emberiza schoeniclus")
Bird.create!(:name => "Eurasian Tree Sparrow", :scientific_name => "Passer montanus")
Bird.create!(:name => "Rook", :scientific_name => "Corvus frugilegus")
Bird.create!(:name => "European Robin", :scientific_name => "Erithacus rubecula")
Bird.create!(:name => "Bar-tailed Godwit", :scientific_name => "Limosa lapponica")
Bird.create!(:name => "Dark-bellied Brent Goose", :scientific_name => "Branta bernicla")
Bird.create!(:name => "Eurasian Oystercatcher", :scientific_name => "Haematopus ostralegus")
Bird.create!(:name => "Eurasian Siskin", :scientific_name => "Carduelis spinus")
Bird.create!(:name => "Northern Shoveler", :scientific_name => "Anas clypeata")
Bird.create!(:name => "Eurasian Wigeon", :scientific_name => "Anas penelope")
Bird.create!(:name => "Eurasian Sparrow Hawk", :scientific_name => "Accipiter nisus")
Bird.create!(:name => "Icterine Warbler", :scientific_name => "Hippolais icterina")
Bird.create!(:name => "Common Starling", :scientific_name => "Sturnus vulgaris")
Bird.create!(:name => "Long-tailed Tit", :scientific_name => "Aegithalos caudatus")
Bird.create!(:name => "Ruddy Turnstone", :scientific_name => "Arenaria interpres")
Bird.create!(:name => "Mew Gull", :scientific_name => "Larus canus")
Bird.create!(:name => "Common Pochard", :scientific_name => "Aythya ferina")
Bird.create!(:name => "Common Chiffchaff", :scientific_name => "Phylloscopus collybita")
Bird.create!(:name => "Greater Scaup", :scientific_name => "Aythya marila")
Bird.create!(:name => "Common Kestrel", :scientific_name => "Falco tinnunculus")
Bird.create!(:name => "Garden Warbler", :scientific_name => "Sylvia borin")
Bird.create!(:name => "Eurasian Collared Dove", :scientific_name => "Streptopelia decaocto")
Bird.create!(:name => "Eurasian Skylark", :scientific_name => "Alauda arvensis")
Bird.create!(:name => "Common Chaffinch", :scientific_name => "Fringilla coelebs")
Bird.create!(:name => "Common Moorhen", :scientific_name => "Gallinula chloropus")
Bird.create!(:name => "Water Pipit", :scientific_name => "Anthus spinoletta")
Bird.create!(:name => "Mallard", :scientific_name => "Anas platyrhynchos")
Bird.create!(:name => "Winter Wren", :scientific_name => "Troglodytes troglodytes")
Bird.create!(:name => "Common Teal", :scientific_name => "Anas crecca")
Bird.create!(:name => "Green Sandpiper", :scientific_name => "Tringa ochropus")
Bird.create!(:name => "White Wagtail", :scientific_name => "Motacilla alba")
Bird.create!(:name => "Eurasian Curlew", :scientific_name => "Numenius arquata")
Bird.create!(:name => "Song Thrush", :scientific_name => "Turdus philomelos")
Bird.create!(:name => "European Herring Gull", :scientific_name => "Larus argentatus")
Bird.create!(:name => "Grey Plover", :scientific_name => "Pluvialis squatarola")
Bird.create!(:name => "Carrion Crow", :scientific_name => "Corvus corone")
Bird.create!(:name => "Coal Tit", :scientific_name => "Periparus ater")
Bird.create!(:name => "Spotted Redshank", :scientific_name => "Tringa erythropus")
Bird.create!(:name => "Blackcap", :scientific_name => "Sylvia atricapilla")
Bird.create!(:name => "Egyptian Vulture", :scientific_name => "Neophron percnopterus")
Bird.create!(:name => "Razorbill", :scientific_name => "Alca torda")
Bird.create!(:name => "Alpine Swift", :scientific_name => "Apus melba")
Bird.create!(:name => "Long-legged Buzzard", :scientific_name => "Buteo rufinus")
Bird.create!(:name => "Audouin`s Gull", :scientific_name => "Larus audouinii")
Bird.create!(:name => "Balearic Shearwater", :scientific_name => "Puffinus mauretanicus")
Bird.create!(:name => "Upland Sandpiper", :scientific_name => "Bartramia longicauda")
Bird.create!(:name => "Greater Spotted Eagle", :scientific_name => "Aquila clanga")
Bird.create!(:name => "Ring Ouzel", :scientific_name => "Turdus torquatus")
Bird.create!(:name => "Yellow-browed Warbler", :scientific_name => "Phylloscopus inornatus")
Bird.create!(:name => "Blue Rock Thrush", :scientific_name => "Monticola solitarius")
Bird.create!(:name => "Buff-breasted Sandpiper", :scientific_name => "Tryngites subruficollis")
Bird.create!(:name => "Jack Snipe", :scientific_name => "Lymnocryptes minimus")
Bird.create!(:name => "White-rumped Sandpiper", :scientific_name => "Calidris fuscicollis")
Bird.create!(:name => "Ruddy Shelduck", :scientific_name => "Tadorna ferruginea")
Bird.create!(:name => "Cetti's Warbler", :scientific_name => "Cettia cetti")
Bird.create!(:name => "Citrine Wagtail", :scientific_name => "Motacilla citreola")
Bird.create!(:name => "Roseate Tern", :scientific_name => "Sterna dougallii")
Bird.create!(:name => "Black-legged Kittiwake", :scientific_name => "Rissa tridactyla")
Bird.create!(:name => "Pygmy Cormorant", :scientific_name => "Phalacrocorax pygmeus")
Bird.create!(:name => "Booted Eagle", :scientific_name => "Aquila pennata")
Bird.create!(:name => "Lesser White-fronted Goose", :scientific_name => "Anser erythropus")
Bird.create!(:name => "Little Bunting", :scientific_name => "Emberiza pusilla")
Bird.create!(:name => "Eleonora's Falcon", :scientific_name => "Falco eleonorae")
Bird.create!(:name => "European Serin", :scientific_name => "Serinus serinus")
Bird.create!(:name => "Twite", :scientific_name => "Carduelis flavirostris")
Bird.create!(:name => "Yellow-legged Gull", :scientific_name => "Larus michahellis")
Bird.create!(:name => "Gyr Falcon", :scientific_name => "Falco rusticolus")
Bird.create!(:name => "Greenish Warbler", :scientific_name => "Phylloscopus trochiloides")
Bird.create!(:name => "Red-necked Phalarope", :scientific_name => "Phalaropus lobatus")
Bird.create!(:name => "Mealy Redpoll", :scientific_name => "Carduelis flammea")
Bird.create!(:name => "Glaucous Gull", :scientific_name => "Larus hyperboreus")
Bird.create!(:name => "Great Skua", :scientific_name => "Stercorarius skua")
Bird.create!(:name => "Great Bustard", :scientific_name => "Otis tarda")
Bird.create!(:name => "Velvet Scoter", :scientific_name => "Melanitta fusca")
Bird.create!(:name => "Pine Grosbeak", :scientific_name => "Pinicola enucleator")
Bird.create!(:name => "House Crow", :scientific_name => "Corvus splendens")
Bird.create!(:name => "Hume`s Leaf Warbler", :scientific_name => "Phylloscopus humei")
Bird.create!(:name => "Great Northern Loon", :scientific_name => "Gavia immer")
Bird.create!(:name => "Long-tailed Duck", :scientific_name => "Clangula hyemalis")
Bird.create!(:name => "Lapland Longspur", :scientific_name => "Calcarius lapponicus")
Bird.create!(:name => "Northern Gannet", :scientific_name => "Morus bassanus")
Bird.create!(:name => "Eastern Imperial Eagle", :scientific_name => "Aquila heliaca")
Bird.create!(:name => "Little Auk", :scientific_name => "Alle alle")
Bird.create!(:name => "Lesser Spotted Woodpecker", :scientific_name => "Dendrocopos minor")
Bird.create!(:name => "Iceland Gull", :scientific_name => "Larus glaucoides")
Bird.create!(:name => "Parasitic Jaeger", :scientific_name => "Stercorarius parasiticus")
Bird.create!(:name => "Bewick`s Swan", :scientific_name => "Cygnus bewickii")
Bird.create!(:name => "Little Bustard", :scientific_name => "Tetrax tetrax")
Bird.create!(:name => "Little Crake", :scientific_name => "Porzana parva")
Bird.create!(:name => "Baillon`s Crake", :scientific_name => "Porzana pusilla")
Bird.create!(:name => "Long-tailed Jaeger", :scientific_name => "Stercorarius longicaudus")
Bird.create!(:name => "King Eider", :scientific_name => "Somateria spectabilis")
Bird.create!(:name => "Greater Short-toed Lark", :scientific_name => "Calandrella brachydactyla")
Bird.create!(:name => "Houbara Bustard", :scientific_name => "Chlamydotis undulata")
Bird.create!(:name => "Curlew Sandpiper", :scientific_name => "Calidris ferruginea")
Bird.create!(:name => "Common Crossbill", :scientific_name => "Loxia curvirostra")
Bird.create!(:name => "European Shag", :scientific_name => "Phalacrocorax aristotelis")
Bird.create!(:name => "Horned Grebe", :scientific_name => "Podiceps auritus")
Bird.create!(:name => "Common Quail", :scientific_name => "Coturnix coturnix")
Bird.create!(:name => "Bearded Vulture", :scientific_name => "Gypaetus barbatus")
Bird.create!(:name => "Lanner Falcon", :scientific_name => "Falco biarmicus")
Bird.create!(:name => "Middle Spotted Woodpecker", :scientific_name => "Dendrocopos medius")
Bird.create!(:name => "Pomarine Jaeger", :scientific_name => "Stercorarius pomarinus")
Bird.create!(:name => "Red-breasted Merganser", :scientific_name => "Mergus serrator")
Bird.create!(:name => "Eurasian Black Vulture", :scientific_name => "Aegypius monachus")
Bird.create!(:name => "Eurasian Dotterel", :scientific_name => "Charadrius morinellus")
Bird.create!(:name => "Common Nightingale", :scientific_name => "Luscinia megarhynchos")
Bird.create!(:name => "Northern willow warbler", :scientific_name => "Phylloscopus trochilus acredula")
Bird.create!(:name => "Manx Shearwater", :scientific_name => "Puffinus puffinus")
Bird.create!(:name => "Northern Fulmar", :scientific_name => "Fulmarus glacialis")
Bird.create!(:name => "Eurasian Eagle Owl", :scientific_name => "Bubo bubo")
Bird.create!(:name => "Orphean Warbler", :scientific_name => "Sylvia hortensis")
Bird.create!(:name => "Melodious Warbler", :scientific_name => "Hippolais polyglotta")
Bird.create!(:name => "Pallas's Leaf Warbler", :scientific_name => "Phylloscopus proregulus")
Bird.create!(:name => "Atlantic Puffin", :scientific_name => "Fratercula arctica")
Bird.create!(:name => "Black-throated Loon", :scientific_name => "Gavia arctica")
Bird.create!(:name => "Bohemian Waxwing", :scientific_name => "Bombycilla garrulus")
Bird.create!(:name => "Marsh Sandpiper", :scientific_name => "Tringa stagnatilis")
Bird.create!(:name => "Great Snipe", :scientific_name => "Gallinago media")
Bird.create!(:name => "Squacco Heron", :scientific_name => "Ardeola ralloides")
Bird.create!(:name => "Long-eared Owl", :scientific_name => "Asio otus")
Bird.create!(:name => "Caspian Tern", :scientific_name => "Hydroprogne caspia")
Bird.create!(:name => "Red-breasted Goose", :scientific_name => "Branta ruficollis")
Bird.create!(:name => "Red-throated Loon", :scientific_name => "Gavia stellata")
Bird.create!(:name => "Common Rosefinch", :scientific_name => "Carpodacus erythrinus")
Bird.create!(:name => "Red-footed Falcon", :scientific_name => "Falco vespertinus")
Bird.create!(:name => "Ross's Goose", :scientific_name => "Anser rossii")
Bird.create!(:name => "Red Phalarope", :scientific_name => "Phalaropus fulicarius")
Bird.create!(:name => "Pied Wagtail", :scientific_name => "Motacilla yarrellii")
Bird.create!(:name => "Rose-coloured Starling", :scientific_name => "Sturnus roseus")
Bird.create!(:name => "Rough-legged Buzzard", :scientific_name => "Buteo lagopus")
Bird.create!(:name => "Saker Falcon", :scientific_name => "Falco cherrug")
Bird.create!(:name => "European Roller", :scientific_name => "Coracias garrulus")
Bird.create!(:name => "Short-toed Eagle", :scientific_name => "Circaetus gallicus")
Bird.create!(:name => "Peregrine Falcon", :scientific_name => "Falco peregrinus")
Bird.create!(:name => "Merlin", :scientific_name => "Falco columbarius")
Bird.create!(:name => "Snow Goose", :scientific_name => "Anser caerulescens")
Bird.create!(:name => "Snowy Owl", :scientific_name => "Bubo scandiacus")
Bird.create!(:name => "Snow Bunting", :scientific_name => "Plectrophenax nivalis")
Bird.create!(:name => "Common Grasshopper Warbler", :scientific_name => "Locustella naevia")
Bird.create!(:name => "Golden Eagle", :scientific_name => "Aquila chrysaetos")
Bird.create!(:name => "Black-winged Stilt", :scientific_name => "Himantopus himantopus")
Bird.create!(:name => "Steppe Eagle", :scientific_name => "Aquila nipalensis")
Bird.create!(:name => "Pallid Harrier", :scientific_name => "Circus macrourus")
Bird.create!(:name => "European Storm-petrel", :scientific_name => "Hydrobates pelagicus")
Bird.create!(:name => "Horned Lark", :scientific_name => "Eremophila alpestris")
Bird.create!(:name => "Eurasian Treecreeper", :scientific_name => "Certhia familiaris")
Bird.create!(:name => "Taiga Bean Goose", :scientific_name => "Anser fabalis")
Bird.create!(:name => "Temminck`s Stint", :scientific_name => "Calidris temminckii")
Bird.create!(:name => "Terek Sandpiper", :scientific_name => "Xenus cinereus")
Bird.create!(:name => "Tundra Bean Goose", :scientific_name => "Anser serrirostris")
Bird.create!(:name => "European Turtle Dove", :scientific_name => "Streptopelia turtur")
Bird.create!(:name => "Leach`s Storm-petrel", :scientific_name => "Oceanodroma leucorhoa")
Bird.create!(:name => "Eurasian Griffon Vulture", :scientific_name => "Gyps fulvus")
Bird.create!(:name => "Paddyfield Warbler", :scientific_name => "Acrocephalus agricola")
Bird.create!(:name => "Osprey", :scientific_name => "Pandion haliaetus")
Bird.create!(:name => "Firecrest", :scientific_name => "Regulus ignicapilla")
Bird.create!(:name => "Water Rail", :scientific_name => "Rallus aquaticus")
Bird.create!(:name => "European Honey Buzzard", :scientific_name => "Pernis apivorus")
Bird.create!(:name => "Eurasian Golden Oriole", :scientific_name => "Oriolus oriolus")
Bird.create!(:name => "Whooper Swan", :scientific_name => "Cygnus cygnus")
Bird.create!(:name => "Two-barred Crossbill", :scientific_name => "Loxia leucoptera")
Bird.create!(:name => "White-tailed Eagle", :scientific_name => "Haliaeetus albicilla")
Bird.create!(:name => "Atlantic Murre", :scientific_name => "Uria aalge")
Bird.create!(:name => "Garganey", :scientific_name => "Anas querquedula")
Bird.create!(:name => "Black Redstart", :scientific_name => "Phoenicurus ochruros")
Bird.create!(:name => "Common Scoter", :scientific_name => "Melanitta nigra")
Bird.create!(:name => "Rock Pipit", :scientific_name => "Anthus petrosus")
Bird.create!(:name => "Lesser Spotted Eagle", :scientific_name => "Aquila pomarina")
Bird.create!(:name => "Cattle Egret", :scientific_name => "Bubulcus ibis")
Bird.create!(:name => "White-winged Black Tern", :scientific_name => "Chlidonias leucopterus")
Bird.create!(:name => "Black Stork", :scientific_name => "Ciconia nigra")
Bird.create!(:name => "Mediterranean Gull", :scientific_name => "Larus melanocephalus")
Bird.create!(:name => "Black Kite", :scientific_name => "Milvus migrans")
Bird.create!(:name => "Yellow Wagtail", :scientific_name => "Motacilla flavissima")
Bird.create!(:name => "Red-necked Grebe", :scientific_name => "Podiceps grisegena")
Bird.create!(:name => "Gull-billed Tern", :scientific_name => "Gelochelidon nilotica")
Bird.create!(:name => "Pectoral Sandpiper", :scientific_name => "Calidris melanotos")
Bird.create!(:name => "Barred Warbler", :scientific_name => "Sylvia nisoria")
Bird.create!(:name => "Red-throated Pipit", :scientific_name => "Anthus cervinus")
Bird.create!(:name => "Grey Wagtail", :scientific_name => "Motacilla cinerea")
Bird.create!(:name => "Richard`s Pipit", :scientific_name => "Anthus richardi")
Bird.create!(:name => "Black Woodpecker", :scientific_name => "Dryocopus martius")
Bird.create!(:name => "Little Ringed Plover", :scientific_name => "Charadrius dubius")
Bird.create!(:name => "Whiskered Tern", :scientific_name => "Chlidonias hybrida")
Bird.create!(:name => "Lesser Redpoll", :scientific_name => "Carduelis cabaret")
Bird.create!(:name => "Pallas' Bunting", :scientific_name => "Emberiza pallasi")
Bird.create!(:name => "Ferruginous Duck", :scientific_name => "Aythya nyroca")
Bird.create!(:name => "Whistling Swan", :scientific_name => "Cygnus columbianus")
Bird.create!(:name => "Black Brant", :scientific_name => "Branta nigricans")
Bird.create!(:name => "Marbled Teal", :scientific_name => "Marmaronetta angustirostris")
Bird.create!(:name => "Canvasback", :scientific_name => "Aythya valisineria")
Bird.create!(:name => "Redhead", :scientific_name => "Aythya americana")
Bird.create!(:name => "Lesser Scaup", :scientific_name => "Aythya affinis")
Bird.create!(:name => "Steller`s Eider", :scientific_name => "Polysticta stelleri")
Bird.create!(:name => "Spectacled Eider", :scientific_name => "Somateria fischeri")
Bird.create!(:name => "Harlequin Duck", :scientific_name => "Histronicus histrionicus")
Bird.create!(:name => "Black Scoter", :scientific_name => "Melanitta americana")
Bird.create!(:name => "Surf Scoter", :scientific_name => "Melanitta perspicillata")
Bird.create!(:name => "Barrow`s Goldeneye", :scientific_name => "Bucephala islandica")
Bird.create!(:name => "Falcated Duck", :scientific_name => "Anas falcata")
Bird.create!(:name => "American Wigeon", :scientific_name => "Anas americana")
Bird.create!(:name => "Blue-winged Teal", :scientific_name => "Anas discors")
Bird.create!(:name => "American Black Duck", :scientific_name => "Anas rubripes")
Bird.create!(:name => "Baikal Teal", :scientific_name => "Anas formosa")
Bird.create!(:name => "Green-Winged Teal", :scientific_name => "Anas carolinensis")
Bird.create!(:name => "Hazel Grouse", :scientific_name => "Bonasa bonasia")
Bird.create!(:name => "Rock Partridge", :scientific_name => "Alectoris graeca")
Bird.create!(:name => "Red-legged Partridge", :scientific_name => "Alectoris rufa")
Bird.create!(:name => "Yellow-billed Loon", :scientific_name => "Gavia adamsii")
Bird.create!(:name => "Cory`s Shearwater", :scientific_name => "Calonectris borealis")
Bird.create!(:name => "Madeiran Storm-Petrel", :scientific_name => "Oceanodroma castro")
Bird.create!(:name => "Great White Pelican", :scientific_name => "Pelecanus onocrotalus")
Bird.create!(:name => "Dalmatian Pelican", :scientific_name => "Pelecanus crispus")
Bird.create!(:name => "American Bittern", :scientific_name => "Botaurus lentiginosus")
Bird.create!(:name => "Glossy Ibis", :scientific_name => "Plegadis falcinellus")
Bird.create!(:name => "Spanish Imperial Eagle", :scientific_name => "Aquila adalberti")
Bird.create!(:name => "Lesser Kestrel", :scientific_name => "Falco naumanni")
Bird.create!(:name => "Houbara Bustard", :scientific_name => "Chlamydotis undulata")
Bird.create!(:name => "Crab-Plover", :scientific_name => "Dromas ardeola")
Bird.create!(:name => "Cream-coloured Courser", :scientific_name => "Cursorius cursor")
Bird.create!(:name => "Collared Pratincole", :scientific_name => "Glareola pratincola")
Bird.create!(:name => "Black-winged Pratincole", :scientific_name => "Glareola nordmanni")
Bird.create!(:name => "Killdeer", :scientific_name => "Charadrius vociferus")
Bird.create!(:name => "Lesser Sand Plover", :scientific_name => "Charadrius mongolus")
Bird.create!(:name => "Greater Sand Plover", :scientific_name => "Charadrius leschenaultii")
Bird.create!(:name => "Caspian Plover", :scientific_name => "Charadrius asiaticus")
Bird.create!(:name => "American Golden Plover", :scientific_name => "Pluvialis dominica")
Bird.create!(:name => "Pacific Golden Plover", :scientific_name => "Pluvialis fulva")
Bird.create!(:name => "Sharp-tailed Sandpiper", :scientific_name => "Calidris acuminata")
Bird.create!(:name => "Broad-billed Sandpiper", :scientific_name => "Limicola falcinellus")
Bird.create!(:name => "Spoon-Billed Sandpiper", :scientific_name => "Eurynorhynchus pygmaeus")
Bird.create!(:name => "Short-Billed Dowitcher", :scientific_name => "Limnodromus griseus")
Bird.create!(:name => "Long-billed Dowitcher", :scientific_name => "Limnodromus scolopaceus")
Bird.create!(:name => "Hudsonian Godwit", :scientific_name => "Limosa haemastica")
Bird.create!(:name => "Little Curlew", :scientific_name => "Numenius minutus")
Bird.create!(:name => "Lesser Yellowlegs", :scientific_name => "Tringa flavipes")
Bird.create!(:name => "Wilson`s Phalarope", :scientific_name => "Phalaropus tricolor")
Bird.create!(:name => "Pallas`s Gull", :scientific_name => "Larus ichthyaetus")
Bird.create!(:name => "Laughing Gull", :scientific_name => "Larus atricilla")
Bird.create!(:name => "Franklin`s Gull", :scientific_name => "Larus pipixcan")
Bird.create!(:name => "Bonaparte`s Gull", :scientific_name => "Larus philadelphia")
Bird.create!(:name => "Ring-billed Gull", :scientific_name => "Larus delawarensis")
Bird.create!(:name => "American Herring Gull", :scientific_name => "Larus smithsonianus")
Bird.create!(:name => "Caspian Gull", :scientific_name => "Larus cachinnans")
Bird.create!(:name => "Ivory Gull", :scientific_name => "Pagophila eburnea")
Bird.create!(:name => "Royal Tern", :scientific_name => "Sterna maxima")
Bird.create!(:name => "Brünnich`s Murre", :scientific_name => "Uria lomvia")
Bird.create!(:name => "Crested Auklet", :scientific_name => "Aethia cristatella")
Bird.create!(:name => "Parakeet Auklet", :scientific_name => "Cyclorrhynchus psittacula")
Bird.create!(:name => "Tufted Puffin", :scientific_name => "Lunda cirrhata")
Bird.create!(:name => "Laughing Dove", :scientific_name => "Streptopelia senegalensis")
Bird.create!(:name => "Great Spotted Cuckoo", :scientific_name => "Clamator glandarius")
Bird.create!(:name => "Great Grey Owl", :scientific_name => "Strix nebulosa")
Bird.create!(:name => "Tengmalm`s Owl", :scientific_name => "Aegolius funereus")
Bird.create!(:name => "Red-Necked Nightjar", :scientific_name => "Caprimulgus ruficollis")
Bird.create!(:name => "Chimney Swift", :scientific_name => "Chaetura pelagica")
Bird.create!(:name => "Green Bea-Eater", :scientific_name => "Merops orientalis")
Bird.create!(:name => "Grey-headed Woodpecker", :scientific_name => "Picus canus")
Bird.create!(:name => "Lesser Short-Toed Lark", :scientific_name => "Calandrella rufescens")
Bird.create!(:name => "Eurasian Crag Martin", :scientific_name => "Hirundo rupestris")
Bird.create!(:name => "Red-rumped Swallow", :scientific_name => "Cecropis daurica")
Bird.create!(:name => "Blyth`s Pipit", :scientific_name => "Anthus godlewskii")
Bird.create!(:name => "Pechora Pipit", :scientific_name => "Anthus gustavi")
Bird.create!(:name => "Grey-headed Wagtail", :scientific_name => "Motacilla thunbergi")
Bird.create!(:name => "Yellow-Headed Wagtail", :scientific_name => "Motacilla lutea")
Bird.create!(:name => "White-throated Dipper", :scientific_name => "Cinclus cinclus")
Bird.create!(:name => "Rufous-Tailed Scrub Robin", :scientific_name => "Cercotrichas galactotes")
Bird.create!(:name => "Thrush Nightingale", :scientific_name => "Luscinia luscinia")
Bird.create!(:name => "White-throated Robin", :scientific_name => "Irania gutturalis")
Bird.create!(:name => "Caspian Stonechat", :scientific_name => "Saxicola maura variegata")
Bird.create!(:name => "Western Black-eared Wheatear", :scientific_name => "Oenanthe hispanica")
Bird.create!(:name => "Rufous-tailed Rock Thrush", :scientific_name => "Monticola saxatilis")
Bird.create!(:name => "Red-throated Thrush/Black-throated", :scientific_name => "Turdus ruficollis")
Bird.create!(:name => "American Robin", :scientific_name => "Turdus migratorius")
Bird.create!(:name => "Zitting Cisticola", :scientific_name => "Cisticola juncidis")
Bird.create!(:name => "Lanceolated Warbler", :scientific_name => "Locustella lanceolata")
Bird.create!(:name => "River Warbler", :scientific_name => "Locustella fluviatilis")
Bird.create!(:name => "Blyth`s Reed Warbler", :scientific_name => "Acrocephalus dumetorum")
Bird.create!(:name => "Caspian Reed Warbler", :scientific_name => "Acrocephalus fuscus")
Bird.create!(:name => "Aquatic Warbler", :scientific_name => "Acrocephalus paludicola")
Bird.create!(:name => "Booted Warbler", :scientific_name => "Acrocephalus caligatus")
Bird.create!(:name => "Marmora's Warbler", :scientific_name => "Sylvia sarda")
Bird.create!(:name => "Dartford Warbler", :scientific_name => "Sylvia undata")
Bird.create!(:name => "Subalpine Warbler", :scientific_name => "Sylvia cantillans")
Bird.create!(:name => "Ménétries's Warbler", :scientific_name => "Sylvia mystacea")
Bird.create!(:name => "Rüppel's Warbler", :scientific_name => "Sylvia rueppelli")
Bird.create!(:name => "Asian Desert Warbler", :scientific_name => "Sylvia nana")
Bird.create!(:name => "Western Orphean Warbler", :scientific_name => "Sylvia hortensis hortensis")
Bird.create!(:name => "Arctic Warbler", :scientific_name => "Phylloscopus borealis")
Bird.create!(:name => "Radde`s Warbler", :scientific_name => "Phylloscopus schwarzi")
Bird.create!(:name => "Western Bonelli`s Warbler", :scientific_name => "Phylloscopus bonelli")
Bird.create!(:name => "Red-breasted Flycatcher", :scientific_name => "Ficedula parva")
Bird.create!(:name => "Eurasian Penduline Tit", :scientific_name => "Remiz pendulinus")
Bird.create!(:name => "Daurian Shrike", :scientific_name => "Lanius isabellinus")
Bird.create!(:name => "Long-Tailed Shrike", :scientific_name => "Lanius schach")
Bird.create!(:name => "Lesser Grey Shrike", :scientific_name => "Lanius minor")
Bird.create!(:name => "Southern Grey Shrike", :scientific_name => "Lanius meridionalis")
Bird.create!(:name => "Masked Shrike", :scientific_name => "Lanius nubicus")
Bird.create!(:name => "Spotted Nutcracker", :scientific_name => "Nucifraga caryocatactes")
Bird.create!(:name => "Daurian Jackdaw", :scientific_name => "Corvus dauuricus")
Bird.create!(:name => "Purple-Backed Starling", :scientific_name => "Sturnus sturninus")
Bird.create!(:name => "Red-Fronted Serin", :scientific_name => "Serinus pusillus")
Bird.create!(:name => "Arctic Redpoll", :scientific_name => "Carduelis hornemanni")
Bird.create!(:name => "Scottish Crossbill", :scientific_name => "Loxia scotica")
Bird.create!(:name => "Parrot Crossbill", :scientific_name => "Loxia pytyopsittacus")
Bird.create!(:name => "Black-faced Bunting", :scientific_name => "Emberiza spodocephala")
Bird.create!(:name => "Pink-footed Goose", :scientific_name => "Anser brachyrhynchus")
Bird.create!(:name => "Black-winged Kite", :scientific_name => "Elanus caeruleus")
Bird.create!(:name => "European Bee-eater", :scientific_name => "Merops apiaster")
Bird.create!(:name => "Sabine`s Gull", :scientific_name => "Larus sabini")
Bird.create!(:name => "Sooty Shearwater", :scientific_name => "Puffinus griseus")
Bird.create!(:name => "Lesser Canada Goose", :scientific_name => "Branta hutchinsii")
Bird.create!(:name => "Ring-necked Duck", :scientific_name => "Aythya collaris")
Bird.create!(:name => "Greater Flamingo", :scientific_name => "Phoenicopterus roseus")
Bird.create!(:name => "Iberian Chiffchaff", :scientific_name => "Phylloscopus ibericus")
Bird.create!(:name => "Ashy-headed Wagtail", :scientific_name => "Motacilla cinereocapilla")
Bird.create!(:name => "Stilt Sandpiper", :scientific_name => "Calidris himantopus")
Bird.create!(:name => "Siberian Stonechat", :scientific_name => "Saxicola maurus")
Bird.create!(:name => "Greater Yellowlegs", :scientific_name => "Tringa melanoleuca")
Bird.create!(:name => "Forster`s Tern", :scientific_name => "Sterna forsteri")
Bird.create!(:name => "Dusky Warbler", :scientific_name => "Phylloscopus fuscatus")
Bird.create!(:name => "Cirl Bunting", :scientific_name => "Emberiza cirlus")
Bird.create!(:name => "Olive-backed Pipit", :scientific_name => "Anthus hodgsoni")
Bird.create!(:name => "Sociable Lapwing", :scientific_name => "Vanellus gregarius")
Bird.create!(:name => "Spotted Sandpiper", :scientific_name => "Actitis macularius")
Bird.create!(:name => "Baird`s Sandpiper", :scientific_name => "Calidris bairdii")
Bird.create!(:name => "Rustic Bunting", :scientific_name => "Emberiza rustica")
Bird.create!(:name => "Yellow-browed Bunting", :scientific_name => "Emberiza chrysophrys")
Bird.create!(:name => "Great Shearwater", :scientific_name => "Puffinus gravis")
Bird.create!(:name => "Bonelli`s Eagle", :scientific_name => "Aquila fasciata")
Bird.create!(:name => "Calandra Lark", :scientific_name => "Melanocorypha calandra")
Bird.create!(:name => "Sardinian Warbler", :scientific_name => "Sylvia melanocephala")
Bird.create!(:name => "Ross's Gull", :scientific_name => "Larus roseus")
Bird.create!(:name => "Yellow-Breasted Bunting", :scientific_name => "Emberiza aureola")
Bird.create!(:name => "Pine Bunting", :scientific_name => "Emberiza leucocephalos")
Bird.create!(:name => "Black Guillemot", :scientific_name => "Cepphus grylle")
Bird.create!(:name => "Pied-billed Grebe", :scientific_name => "Podilymbus podiceps")
Bird.create!(:name => "Soft-plumaged Petrel", :scientific_name => "Pterodroma mollis")
Bird.create!(:name => "Bulwer's Petrel", :scientific_name => "Bulweria bulwerii")
Bird.create!(:name => "White-Faced Storm-Petrel", :scientific_name => "Pelagodroma marina")
Bird.create!(:name => "Pallas’s Fish Eagle", :scientific_name => "Haliaeetus leucoryphus")
Bird.create!(:name => "Sandhill Crane", :scientific_name => "Grus canadensis")
Bird.create!(:name => "Macqueen’s Bustard", :scientific_name => "Chlamydotis macqueenii")
Bird.create!(:name => "White-tailed Lapwing", :scientific_name => "Vanellus leucurus")
Bird.create!(:name => "Great Knot", :scientific_name => "Calidris tenuirostris")
Bird.create!(:name => "Semipalmated Sandpiper", :scientific_name => "Calidris pusilla")
Bird.create!(:name => "Red-necked Stint", :scientific_name => "Calidris ruficollis")
Bird.create!(:name => "Slender-billed Curlew", :scientific_name => "Numenius tenuirostris")
Bird.create!(:name => "Bridled Tern", :scientific_name => "Onychoprion anaethetus")
Bird.create!(:name => "Pallas’s Sandgrouse", :scientific_name => "Syrrhaptes paradoxus")
Bird.create!(:name => "European Scops Owl", :scientific_name => "Otus scops")
Bird.create!(:name => "Northern Hawk Owl", :scientific_name => "Surnia ulula")
Bird.create!(:name => "White-Throated Needletail", :scientific_name => "Hirundapus caudacutus")
Bird.create!(:name => "Belted Kingfisher", :scientific_name => "Ceryle alcyon")
Bird.create!(:name => "Blue-cheeked Bee-eater", :scientific_name => "Merops persicus")
Bird.create!(:name => "Black-headed Wagtail", :scientific_name => "Motacilla feldegg")
Bird.create!(:name => "Northern Mockingbird", :scientific_name => "Mimus polyglottos")
Bird.create!(:name => "Alpine Accentor", :scientific_name => "Prunella collaris")
Bird.create!(:name => "Red-flanked Bluetail", :scientific_name => "Tarsiger cyanurus")
Bird.create!(:name => "Isabelline Wheatear", :scientific_name => "Oenanthe isabellina")
Bird.create!(:name => "Pied Wheatear", :scientific_name => "Oenanthe pleschanka")
Bird.create!(:name => "Eastern Black-eared Wheatear", :scientific_name => "Oenanthe melanoleuca")
Bird.create!(:name => "Desert Wheatear", :scientific_name => "Oenanthe deserti")
Bird.create!(:name => "White`s Thrush", :scientific_name => "Zoothera aurea")
Bird.create!(:name => "Siberian Thrush", :scientific_name => "Zoothera sibirica")
Bird.create!(:name => "Eyebrowed Thrush", :scientific_name => "Turdus obscurus")
Bird.create!(:name => "Dusky Thrush", :scientific_name => "Turdus eunomus")
Bird.create!(:name => "Black-throated Thrush", :scientific_name => "Turdus atrogularis")
Bird.create!(:name => "Pallas`s Grasshopper Warbler", :scientific_name => "Locustella certhiola")
Bird.create!(:name => "Spectacled Warbler", :scientific_name => "Sylvia conspicillata")
Bird.create!(:name => "Two-barred Warbler", :scientific_name => "Phylloscopus plumbeitarsus")
Bird.create!(:name => "Eastern Bonelli’s Warbler", :scientific_name => "Phylloscopus orientalis")
Bird.create!(:name => "Collared Flycatcher", :scientific_name => "Ficedula albicollis")
Bird.create!(:name => "Wallcreeper", :scientific_name => "Tichodroma muraria")
Bird.create!(:name => "Turkestan Shrike", :scientific_name => "Lanius phoenicuroides")
Bird.create!(:name => "Steppe Grey Shrike", :scientific_name => "Lanius pallidirostris")
Bird.create!(:name => "Spanish Sparrow", :scientific_name => "Passer hispaniolensis")
Bird.create!(:name => "Red-eyed Vireo", :scientific_name => "Vireo olivaceus")
Bird.create!(:name => "Myrtle Warbler", :scientific_name => "Dendroica coronata")
Bird.create!(:name => "White-crowned Sparrow", :scientific_name => "Zonotrichia leucophrys")
Bird.create!(:name => "White-throated Sparrow", :scientific_name => "Zonotrichia albicollis")
Bird.create!(:name => "Cretzschmar`s Bunting", :scientific_name => "Emberiza caesia")
Bird.create!(:name => "Chestnut Bunting", :scientific_name => "Emberiza rutila")
Bird.create!(:name => "Red-headed Bunting", :scientific_name => "Emberiza bruniceps")
Bird.create!(:name => "Black-headed Bunting", :scientific_name => "Emberiza melanocephala")
Bird.create!(:name => "Indigo Bunting", :scientific_name => "Passerina cyanea")
Bird.create!(:name => "Balearic Woodchat Shrike", :scientific_name => "Lanius senator badius")
Bird.create!(:name => "Demoiselle Crane", :scientific_name => "Grus virgo")
Bird.create!(:name => "Chough", :scientific_name => "Pyrrhocorax pyrrhocorax")
Bird.create!(:name => "Red-Billed Chough", :scientific_name => "Pyrrhocorax graculus")
Bird.create!(:name => "Elegant Tern", :scientific_name => "Sterna elegans")
Bird.create!(:name => "Chukar", :scientific_name => "Alectoris chukar")
Bird.create!(:name => "Yellow-Billed Cuckoo", :scientific_name => "Coccyzus americanus")
Bird.create!(:name => "American Sandwich Tern", :scientific_name => "Sterna sandvicensis acuflavida")
Bird.create!(:name => "Olive-Tree Warbler", :scientific_name => "Hippolais olivetorum")
Bird.create!(:name => "Eastern Olivaceous Warbler", :scientific_name => "Acrocephalus pallidus")
Bird.create!(:name => "Indian Cormorant", :scientific_name => "Phalacrocorax fuscicollis")
Bird.create!(:name => "Spur-Winged Lapwing", :scientific_name => "Vanellus spinosus")
Bird.create!(:name => "Yelkouan Shearwater", :scientific_name => "Puffinus yelkouan")
Bird.create!(:name => "Trumpeter Finch", :scientific_name => "Bucanetes githagineus")
Bird.create!(:name => "Red Grouse", :scientific_name => "Lagopus scoticus")
Bird.create!(:name => "Rock Ptarmigan", :scientific_name => "Lagopus mutus")
Bird.create!(:name => "Long-Tailed Cormorant", :scientific_name => "Phalacrocorax africanus")
Bird.create!(:name => "Double-crested Cormorant", :scientific_name => "Phalacrocorax auritus")
Bird.create!(:name => "Magnificent Frigatebird", :scientific_name => "Fregata magnificens")
Bird.create!(:name => "Naumann's Thrush", :scientific_name => "Turdus naumanni")
Bird.create!(:name => "Oriental Pratincole", :scientific_name => "Glareola maldivarum")
Bird.create!(:name => "Bufflehead", :scientific_name => "Bucephala albeola")
Bird.create!(:name => "Snowfinch", :scientific_name => "Montifrigilla nivalis")
Bird.create!(:name => "Ural owl", :scientific_name => "Strix uralensis")
Bird.create!(:name => "Spanish Wagtail", :scientific_name => "Motacilla iberiae")
Bird.create!(:name => "Song Sparrow", :scientific_name => "Melospiza melodia")
Bird.create!(:name => "Rock Bunting", :scientific_name => "Emberiza cia")
Bird.create!(:name => "Siberian Rubythroat", :scientific_name => "Luscinia calliope")
Bird.create!(:name => "Pallid Swift", :scientific_name => "Apus pallidus")
Bird.create!(:name => "Eurasian Pygmy Owl", :scientific_name => "Glaucidium passerinum")
Bird.create!(:name => "Madeira Little Shearwater", :scientific_name => "Puffinus baroli")
Bird.create!(:name => "House Finch", :scientific_name => "Carpodacus mexicanus")
Bird.create!(:name => "Green Heron", :scientific_name => "Butorides virescens")
Bird.create!(:name => "Solitary Sandpiper", :scientific_name => "Tringa solitaria")
Bird.create!(:name => "Heuglin's Gull", :scientific_name => "Larus heuglini")

