# User
User.create!(:pseudo => "ahe", :firstname => "Anthony", :lastname => "Heukmes", :email => "ahe@ahe.be", :role => "admin")
User.create!(:pseudo => "willd", :firstname => "Wilfried", :lastname => "Dalmat", :email => "willd@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "marcos", :firstname => "Marcos", :lastname => "Camozzato", :email => "marcos@ahe.be", :role => "defender")
User.create!(:pseudo => "onyewuo", :firstname => "Ogushi", :lastname => "Onyewu", :email => "onyewuo@ahe.be", :role => "defender")
User.create!(:pseudo => "sarrm", :firstname => "Momo", :lastname => "Sarr", :email => "sarrm@ahe.be", :role => "defender")
User.create!(:pseudo => "mulemol", :firstname => "Landry", :lastname => "Mulemo", :email => "mulemol@ahe.be", :role => "defender")
User.create!(:pseudo => "witsela", :firstname => "Axel", :lastname => "Witsel", :email => "witsela@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "defours", :firstname => "Steven", :lastname => "Defour", :email => "defours@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "goreuxr", :firstname => "Reginal", :lastname => "Goreux", :email => "goureux@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "jova", :firstname => "Milan", :lastname => "Jovanovic", :email => "jova@ahe.be", :role => "striker")
User.create!(:pseudo => "decamar", :firstname => "Igor", :lastname => "De Camargo", :email => "decamar@ahe.be", :role => "striker")
User.create!(:pseudo => "mbokani", :firstname => "Dieumerci", :lastname => "Mbokani", :email => "mbokani@ahe.be", :role => "striker")
User.create!(:pseudo => "nicaise", :firstname => "Benjamin", :lastname => "Nicaise", :email => "nicaise@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "bolats", :firstname => "Sinan", :lastname => "Bolat", :email => "bolats@ahe.be", :role => "goalkeeper")
User.create!(:pseudo => "leonb", :firstname => "Leon", :lastname => "Benko", :email => "leonb@ahe.be", :role => "striker")
User.create!(:pseudo => "espi", :firstname => "Aragon", :lastname => "Espinoza", :email => "espi@ahe.be", :role => "goalkeeper")
User.create!(:pseudo => "carce", :firstname => "Medhi", :lastname => "Carcela", :email => "carce@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "manga", :firstname => "Eliaquim", :lastname => "Mangala", :email => "manga@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "miku", :firstname => "Tomislav", :lastname => "Mikulic", :email => "miku@ahe.be", :role => "defender")
User.create!(:pseudo => "maestro", :firstname => "Segio", :lastname => "Conceicao", :email => "maestro@ahe.be", :role => "middlefielder")
User.create!(:pseudo => "bolo", :firstname => "Laszlo", :lastname => "Boloni", :email => "bolo@ahe.be", :role => "trainer")
User.create!(:pseudo => "pesto", :firstname => "Joaquim", :lastname => "Preto", :email => "ahe@ahe.be", :role => "trainer")
User.create!(:pseudo => "pf", :firstname => "Pierre", :lastname => "Francois", :email => "pf@ahe.be", :role => "admin")
User.create!(:pseudo => "moi", :firstname => "Moi", :lastname => "Moi", :email => "moi@ahe.be", :role => "striker")

# Pets
Pet.create!(:name => "Youpi", :user_id => 1)
Pet.create!(:name => "Blouk", :user_id => 1)
Pet.create!(:name => "Pif", :user_id => 1)
Pet.create!(:name => "Paf", :user_id => 2)
Pet.create!(:name => "Meuh", :user_id => 3)
Pet.create!(:name => "Boug", :user_id => 3)
Pet.create!(:name => "Zigg", :user_id => 4)
Pet.create!(:name => "Iop", :user_id => 4)
Pet.create!(:name => "Tcham", :user_id => 4)
Pet.create!(:name => "Outch", :user_id => 5)
Pet.create!(:name => "Tzii", :user_id => 5)
Pet.create!(:name => "Tutu", :user_id => 6)
Pet.create!(:name => "Tata", :user_id => 7)
Pet.create!(:name => "Bobo", :user_id => 7)
Pet.create!(:name => "Bulk", :user_id => 7)
Pet.create!(:name => "Rocky", :user_id => 7)
Pet.create!(:name => "Arnold", :user_id => 8)
Pet.create!(:name => "Miii", :user_id => 9)
Pet.create!(:name => "Tititi", :user_id => 10)
Pet.create!(:name => "Bob", :user_id => 11)
Pet.create!(:name => "Max", :user_id => 12)
Pet.create!(:name => "Poop", :user_id => 12)
Pet.create!(:name => "Bikk", :user_id => 13)
Pet.create!(:name => "Allo", :user_id => 13) 

# Player
Player.create!(:pseudo => "ahe", :firstname => "Anthony", :lastname => "Heukmes", :email => "ahe@ahe.be", :role => "admin")
Player.create!(:pseudo => "willd", :firstname => "Wilfried", :lastname => "Dalmat", :email => "willd@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "marcos", :firstname => "Marcos", :lastname => "Camozzato", :email => "marcos@ahe.be", :role => "defender")
Player.create!(:pseudo => "onyewuo", :firstname => "Ogushi", :lastname => "Onyewu", :email => "onyewuo@ahe.be", :role => "defender")
Player.create!(:pseudo => "sarrm", :firstname => "Momo", :lastname => "Sarr", :email => "sarrm@ahe.be", :role => "defender")
Player.create!(:pseudo => "mulemol", :firstname => "Landry", :lastname => "Mulemo", :email => "mulemol@ahe.be", :role => "defender")
Player.create!(:pseudo => "witsela", :firstname => "Axel", :lastname => "Witsel", :email => "witsela@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "defours", :firstname => "Steven", :lastname => "Defour", :email => "defours@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "goreuxr", :firstname => "Reginal", :lastname => "Goreux", :email => "goureux@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "jova", :firstname => "Milan", :lastname => "Jovanovic", :email => "jova@ahe.be", :role => "striker")
Player.create!(:pseudo => "decamar", :firstname => "Igor", :lastname => "De Camargo", :email => "decamar@ahe.be", :role => "striker")
Player.create!(:pseudo => "mbokani", :firstname => "Dieumerci", :lastname => "Mbokani", :email => "mbokani@ahe.be", :role => "striker")
Player.create!(:pseudo => "nicaise", :firstname => "Benjamin", :lastname => "Nicaise", :email => "nicaise@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "bolats", :firstname => "Sinan", :lastname => "Bolat", :email => "bolats@ahe.be", :role => "goalkeeper")
Player.create!(:pseudo => "leonb", :firstname => "Leon", :lastname => "Benko", :email => "leonb@ahe.be", :role => "striker")
Player.create!(:pseudo => "espi", :firstname => "Aragon", :lastname => "Espinoza", :email => "espi@ahe.be", :role => "goalkeeper")
Player.create!(:pseudo => "carce", :firstname => "Medhi", :lastname => "Carcela", :email => "carce@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "manga", :firstname => "Eliaquim", :lastname => "Mangala", :email => "manga@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "miku", :firstname => "Tomislav", :lastname => "Mikulic", :email => "miku@ahe.be", :role => "defender")
Player.create!(:pseudo => "maestro", :firstname => "Segio", :lastname => "Conceicao", :email => "maestro@ahe.be", :role => "middlefielder")
Player.create!(:pseudo => "bolo", :firstname => "Laszlo", :lastname => "Boloni", :email => "bolo@ahe.be", :role => "trainer")
Player.create!(:pseudo => "pesto", :firstname => "Joaquim", :lastname => "Preto", :email => "ahe@ahe.be", :role => "trainer")
Player.create!(:pseudo => "pf", :firstname => "Pierre", :lastname => "Francois", :email => "pf@ahe.be", :role => "admin")
Player.create!(:pseudo => "moi", :firstname => "Moi", :lastname => "Moi", :email => "moi@ahe.be", :role => "striker")

# Client
Client.create!(:name => "Client 1")
Client.create!(:name => "Client 2")
Client.create!(:name => "Client 3")

# Invheader
Invheader.create!(:invdate => "2007-10-01", :client_id => 1, :amount => "100.00", :tax => "20.00", :total => "120.00", :note => "note 1" )
Invheader.create!(:invdate => "2007-10-03", :client_id => 1, :amount => "200.00", :tax => "40.00", :total => "240.00", :note => "note 2" )
Invheader.create!(:invdate => "2007-10-02", :client_id => 2, :amount => "300.00", :tax => "60.00", :total => "360.00", :note => "note for invoice 3" )
Invheader.create!(:invdate => "2007-10-04", :client_id => 3, :amount => "150.00", :tax => "0.00", :total => "150.00", :note => "no tax" )
Invheader.create!(:invdate => "2007-10-05", :client_id => 3, :amount => "100.00", :tax => "0.00", :total => "100.00", :note => "no tax" )
Invheader.create!(:invdate => "2007-10-05", :client_id => 1, :amount => "50.00", :tax => "10.00", :total => "60.00", :note => nil )
Invheader.create!(:invdate => "2007-10-05", :client_id => 2, :amount => "120.00", :tax => "12.00", :total => "134.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 3, :amount => "200.00", :tax => "0.00", :total => "200.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 1, :amount => "200.00", :tax => "40.00", :total => "240.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 2, :amount => "100.00", :tax => "20.00", :total => "120.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 1, :amount => "600.00", :tax => "120.00", :total => "720.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 2, :amount => "700.00", :tax => "140.00", :total => "840.00", :note => nil )
Invheader.create!(:invdate => "2007-10-06", :client_id => 3, :amount => "1000.00", :tax => "0.00", :total => "1000.00", :note => nil )

# Invline
Invline.create!( :id => 1, :num => 1, :item => "item 1", :qty => "1.00", :unit => "20.00" )
Invline.create!( :id => 1, :num => 2, :item => "item 2", :qty => "2.00", :unit => "40.00" )
Invline.create!( :id => 2, :num => 1, :item => "item 1", :qty => "2.00", :unit => "20.00" )
Invline.create!( :id => 2, :num => 2, :item => "item 2", :qty => "4.00", :unit => "40.00" )
Invline.create!( :id => 3, :num => 1, :item => "item 3", :qty => "1.00", :unit => "100.00" )
Invline.create!( :id => 3, :num => 4, :item => "item 4", :qty => "1.00", :unit => "200.00" )
Invline.create!( :id => 4, :num => 1, :item => "item 1", :qty => "1.00", :unit => "100.00" )
Invline.create!( :id => 4, :num => 2, :item => "item 2", :qty => "1.00", :unit => "50.00" )
Invline.create!( :id => 5, :num => 3, :item => "item 3", :qty => "1.00", :unit => "100.00" )
Invline.create!( :id => 6, :num => 4, :item => "item 4", :qty => "1.00", :unit => "50.00" )
Invline.create!( :id => 7, :num => 1, :item => "item 5", :qty => "2.00", :unit => "10.00" )
Invline.create!( :id => 7, :num => 2, :item => "item 1", :qty => "1.00", :unit => "100.00" )
Invline.create!( :id => 8, :num => 1, :item => "item 3", :qty => "1.00", :unit => "50.00" )
Invline.create!( :id => 8, :num => 2, :item => "item 2", :qty => "1.00", :unit => "120.00" )
Invline.create!( :id => 8, :num => 3, :item => "item 3", :qty => "1.00", :unit => "30.00" )
Invline.create!( :id => 9, :num => 1, :item => "item 6", :qty => "1.00", :unit => "140.00" )
Invline.create!( :id => 9, :num => 2, :item => "item 3", :qty => "1.00", :unit => "60.00" )
Invline.create!( :id => 10, :num => 1, :item => "item 5", :qty => "3.00", :unit => "10.00" )
Invline.create!( :id => 10, :num => 2, :item => "item 4", :qty => "1.00", :unit => "70.00" )
Invline.create!( :id => 11, :num => 1, :item => "item 1", :qty => "2.00", :unit => "100.00" )
Invline.create!( :id => 11, :num => 2, :item => "item 2", :qty => "3.00", :unit => "50.00" )
Invline.create!( :id => 11, :num => 3, :item => "item 3", :qty => "1.00", :unit => "50.00" )
Invline.create!( :id => 11, :num => 4, :item => "item 4", :qty => "1.00", :unit => "200.00" )
Invline.create!( :id => 12, :num => 4, :item => "item 4", :qty => "1.00", :unit => "300.00" )
Invline.create!( :id => 12, :num => 2, :item => "item 2", :qty => "1.00", :unit => "400.00" )
Invline.create!( :id => 13, :num => 13, :item => "item 13", :qty => "1.00", :unit => "1000.00" )
# Item


# Account
Account.create!(:parent_id => nil, :name => "A1" , :acc_num => 100001, :debit => 11, :credit => 12, :balance => 13, :level => 0, :lft => 1, :rgt => 14 ) 
Account.create!(:parent_id => nil, :name => "A11" , :acc_num => 100011, :debit => 111, :credit => 112, :balance => 113, :level => 1, :lft => 2, :rgt => 3 ) 
Account.create!(:parent_id => nil, :name => "A12" , :acc_num => 100012, :debit => 121, :credit => 122, :balance => 123, :level => 1, :lft => 4, :rgt => 11 ) 
Account.create!(:parent_id => nil, :name => "A13" , :acc_num => 100013, :debit => 131, :credit => 132, :balance => 133, :level => 1, :lft => 12, :rgt => 13 ) 
Account.create!(:parent_id => nil, :name => "A121" , :acc_num => 100121, :debit => 1211, :credit => 1212, :balance => 1213, :level => 2, :lft => 5, :rgt => 8 ) 
Account.create!(:parent_id => nil, :name => "A122" , :acc_num => 100122, :debit => 1221, :credit => 1222, :balance => 1223, :level => 2, :lft => 9, :rgt => 10 ) 
Account.create!(:parent_id => nil, :name => "A1211" , :acc_num => 101211, :debit => 12111, :credit => 12112, :balance => 12113, :level => 3, :lft => 6, :rgt => 7 ) 
