class Invheader < ActiveRecord::Base
  belongs_to :client
  has_many :invlines
  
  gridify :demo0101,
    :title          => I18n.t('txt.jqgrid.demo.xml_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50, 
                                        :align => "right"  },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :sort_by        => :id,
    :sort_order     => :desc,
    :rows_per_page  => 10,     
    :paging_choices => [10,20,30],  
    #:autowidth:     => true, 
    #:viewrecords    => true,    
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0102,
    :title          => I18n.t('txt.jqgrid.demo.json_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50, 
                                        :align => "right"  },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0103,
    :title          => I18n.t('txt.jqgrid.demo.once'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    
   # {name:'id',index:'id', width:60, sorttype:"int"},
   # {name:'invdate',index:'invdate', width:90, sorttype:"date"},
   # {name:'name',index:'name', width:100}, 
   # {name:'amount',index:'amount', width:80, align:"right",sorttype:"float"}, 
   # {name:'tax',index:'tax', width:80, align:"right",sorttype:"float"}, 
   # {name:'total',index:'total', width:80,align:"right",sorttype:"float"}, 
   # {name:'note',index:'note', width:150, sortable:false} 
    
    :height         => :auto,
    :rows_per_page  => 20,
    :paging_choices => [10,20,30],
    :pager          => true,
    :load_once      => true
    
  gridify :demo0201,
    :title          => I18n.t('txt.jqgrid.demo.data'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :select_rows    => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0202,
    :title          => I18n.t('txt.jqgrid.demo.get'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :select_rows    => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0203,
    :title          => I18n.t('txt.jqgrid.demo.set'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :select_rows    => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0301,
    :title          => I18n.t('txt.jqgrid.demo.multi'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :select_rows    => true,
    :multi_select   => true,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0302,
    :title          => I18n.t('txt.jqgrid.demo.master'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :select_rows    => "javascript: handleDemo0302",
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0303,
    :title          => I18n.t('txt.jqgrid.demo.subgrid'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
#    :colNames       => [
#                        I18n.t('activerecord.attributes.invheader.id'),
#                        I18n.t('activerecord.attributes.invheader.invdate'),
#                        I18n.t('activerecord.attributes.invheader.client'),
#                        I18n.t('activerecord.attributes.invheader.amount'),
#                        I18n.t('activerecord.attributes.invheader.tax'),
#                        I18n.t('activerecord.attributes.invheader.total'),
#                        I18n.t('activerecord.attributes.invheader.note'),
#                        I18n.t('activerecord.attributes.invheader.closed'),
#                        I18n.t('activerecord.attributes.invheader.ship_via')
#                       ],
#    :colModel       => {
#                         :id       => { :name     => 'id',
#                                        :width    =>  50, 
#                                        :align    => "right" },
#                         :invdate  => { :name  => 'invdate',  
#                                        :width =>  90 },
#                         :name     => { :name  => 'name',
#                                        :width => 100 },
#                         :amount   => { :name  => 'amount',
#                                        :width =>  80,
#                                        :align => "right" },
#                         :tax      => { :name  => 'tax',
#                                        :width =>  80,
#                                        :align => "right" },    
#                         :total    => { :name  => 'total',
#                                        :width =>  80,
#                                        :align => "right" },   
#                         :note     => { :name     => 'note',
#                                        :width    => 150,
#                                        :sortable => false },
#                         :closed   => { :name  => 'closed',
#                                        :width =>  40 },
#                         :ship_via => { :name  => 'ship_via',
#                                        :width =>  40 }
#                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true,
    :sub_grid       => true,
    :sub_grid_url   => "/jqgrid/demo?model=invline&subgrid=true",
    :sub_grid_model => [
                         { 
                           :name  => ['No','Item','Qty','Unit','Line Total'], 
                           :width => [ 55,    200,  80,    80,  80] 
                         } 
                       ]
    
  gridify :demo0304,
    :title          => I18n.t('txt.jqgrid.demo.as_subgrid'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0305,
    :title          => I18n.t('txt.jqgrid.demo.resizing'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 500,
    :width_fit      => :fitted,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0306,
    :title          => I18n.t('txt.jqgrid.demo.big_sets'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0602,
    :title          => I18n.t('txt.jqgrid.demo.json_map'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    #:data_format    => { :repeatitems => false, :id => "0" },
    :select_rows    => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0603,
    :title          => I18n.t('txt.jqgrid.demo.optimize'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    #:data_format    => { :repeatitems => true, :cell => "", :id => "0" },
    :select_rows    => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0801,
    :title          => I18n.t('txt.jqgrid.demo.searching'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :pager          => true
    
  gridify :demo0802,
    :title          => I18n.t('txt.jqgrid.demo.edit_row'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :editable       => true,
    :select_rows    => true, 
    :jqgrid_options => { :edit_url  => "/jqgrid/demo" },
    :sort_by        => :id,
    :sort_order     => :desc,
    :pager          => true
    
  gridify :demo0803,
    :title          => I18n.t('txt.jqgrid.demo.add_row'),
    :url            => "/jqgrid/demo",
    :include        => [ :client ],
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :editable       => true,
    :jqgrid_options => { :edit_url  => "/jqgrid/demo" },
    :sort_by        => :id,
    :sort_order     => :desc,
    :pager          => true
    
  gridify :demo0804,
    :title          => I18n.t('txt.jqgrid.demo.delete_row'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :editable       => true,
    :select_rows    => true, 
    :jqgrid_options => { :edit_url  => "/jqgrid/demo" },
    :sort_by        => :id,
    :sort_order     => :desc,
    :pager          => true
    
  gridify :demo0805,
    :title          => I18n.t('txt.jqgrid.demo.navigator'),
    :url            => "/jqgrid/demo",
    :restful        => true,
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :editable       => true,
    :select_rows    => true, 
    :edit_button    => true,
    :add_button     => true, 
    :delete_button  => true, 
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo1401,
    :title          => I18n.t('txt.jqgrid.demo.api'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true 
    
  gridify :demo1402,
    :title          => I18n.t('txt.jqgrid.demo.rtl'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    #:direction      => "rtl",
    #:recordpos      => "left", 
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true      
    
  gridify :demo1403,
    :title          => I18n.t('txt.jqgrid.demo.reordering'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :arranger       => :sortable,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo1404,
    :title          => I18n.t('txt.jqgrid.demo.chooser'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :arranger       => :chooser,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo1405,
    :title          => I18n.t('txt.jqgrid.demo.validation'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right",
                                        :validations => { :custom => true , 
                                                          :custom_func => "javascript: mycheck" } },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true,  
    :editable       => true,
    :edit_button    => true,
    :add_button     => true, 
    :delete_button  => true
    
  gridify :demo1406,
    :title          => I18n.t('txt.jqgrid.demo.cinput'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100,                                         
                                        :edit_type    => :custom, 
                                        :edit_options => { :custom_element => "javascript: my_input",
                                                           :custom_value   => "javascript: my_value" } },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right" },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true,     
    :editable       => true,
    :inline_edit    => true,
    :add_button     => true, 
    :delete_button  => true      
    
  gridify :demo1407,
    :title               => I18n.t('txt.jqgrid.demo.ajax'),
    :ajax_grid_options   => { :type => "GET" },
    :url                 => "/jqgrid/demo",
    :data_type           => :json,
    :colNames            => [
                              I18n.t('activerecord.attributes.invheader.id'),
                              I18n.t('activerecord.attributes.invheader.invdate'),
                              I18n.t('activerecord.attributes.invheader.client'),
                              I18n.t('activerecord.attributes.invheader.amount'),
                              I18n.t('activerecord.attributes.invheader.tax'),
                              I18n.t('activerecord.attributes.invheader.total'),
                              I18n.t('activerecord.attributes.invheader.note'),
                              I18n.t('activerecord.attributes.invheader.closed'),
                              I18n.t('activerecord.attributes.invheader.ship_via')
                            ],
    :colModel            => {
                              :id       => { :name     => 'id',
                                             :width    =>  50, 
                                             :align    => "right" },
                              :invdate  => { :name  => 'invdate',  
                                             :width =>  90 },
                              :name     => { :name  => 'name',
                                             :width => 100 },
                              :amount   => { :name  => 'amount',
                                             :width =>  80,
                                             :align => "right" },
                              :tax      => { :name  => 'tax',
                                             :width =>  80,
                                             :align => "right" },    
                              :total    => { :name  => 'total',
                                             :width =>  80,
                                             :align => "right" },   
                              :note     => { :name     => 'note',
                                             :width    => 150,
                                             :sortable => false },
                              :closed   => { :name  => 'closed',
                                            :width =>  40 },
                              :ship_via => { :name  => 'ship_via',
                                             :width =>  40 }
                            },
    :width               => 700,
    :height              => :auto,
    :rows_per_page       => 10,
    :paging_choices      => [10,20,30],
    :sort_by             => :invdate,
    :sort_order          => :desc,
    :search_button       => true,  
    :refresh_button      => true,
    :pager               => true      
    
  gridify :demo1409,
    :title               => I18n.t('txt.jqgrid.demo.srows'),
    :url                 => "/jqgrid/demo",
    :data_type           => :json,
    :colNames            => [
                              I18n.t('activerecord.attributes.invheader.id'),
                              I18n.t('activerecord.attributes.invheader.invdate'),
                              I18n.t('activerecord.attributes.invheader.client'),
                              I18n.t('activerecord.attributes.invheader.amount'),
                              I18n.t('activerecord.attributes.invheader.tax'),
                              I18n.t('activerecord.attributes.invheader.total'),
                              I18n.t('activerecord.attributes.invheader.note'),
                              I18n.t('activerecord.attributes.invheader.closed'),
                              I18n.t('activerecord.attributes.invheader.ship_via')
                            ],
    :colModel            => {
                              :id       => { :name     => 'id',
                                             :width    =>  50, 
                                             :align    => "right" },
                              :invdate  => { :name  => 'invdate',  
                                             :width =>  90 },
                              :name     => { :name  => 'name',
                                             :width => 100 },
                              :amount   => { :name  => 'amount',
                                             :width =>  80,
                                             :align => "right" },
                              :tax      => { :name  => 'tax',
                                             :width =>  80,
                                             :align => "right" },    
                              :total    => { :name  => 'total',
                                             :width =>  80,
                                             :align => "right" },   
                              :note     => { :name     => 'note',
                                             :width    => 150,
                                             :sortable => false },
                              :closed   => { :name  => 'closed',
                                            :width =>  40 },
                              :ship_via => { :name  => 'ship_via',
                                             :width =>  40 }
                            },
    :width               => 700,
    :height              => :auto,
    :rows_per_page       => 10,
    :paging_choices      => [10,20,30],
    :sort_by             => :id,
    :sort_order          => :desc,
    :sortable_rows       => true,
    :search_button       => true,  
    :refresh_button      => true,
    :pager               => true           
    
  gridify :demo1411,
    :title          => I18n.t('txt.jqgrid.demo.resizing'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right" },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 600,
    :width_fit      => :fitted,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
end

