class Invheader < ActiveRecord::Base
  belongs_to :client
  has_many :invlines

  gridify :demo0101,
    :title          => I18n.t('txt.jqgrid.demo.20xml_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50,
                                        :align => :right  },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount ',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :search_button  => true,
    :refresh_button => true,
    :pager          => true
    
    
  gridify :demo0102,
    :title          => I18n.t('txt.jqgrid.demo.20json_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50,
                                        :align => :right  },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :search_button  => true,
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0103,
    :title          => I18n.t('txt.jqgrid.demo.20once'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 20,
    :paging_choices => [10,20,30],
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :pager          => true,
    :load_once      => true

  gridify :demo0201,
    :title          => I18n.t('txt.jqgrid.demo.20data'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :select_rows    => true,
    :search_button  => true,
    :refresh_button => true,
    :pager          => true

  gridify :demo0202,
    :title          => I18n.t('txt.jqgrid.demo.20get'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :select_rows    => true,
    :search_button  => true,
    :refresh_button => true,
    :pager          => true

  gridify :demo0203,
    :title          => I18n.t('txt.jqgrid.demo.20set'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :select_rows    => true,
    :search_button  => true,
    :refresh_button => true,
    :pager          => true

  gridify :demo0301,
    :title          => I18n.t('txt.jqgrid.demo.20multi'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :select_rows    => true,
    :multi_select   => true,
    :search_button  => true,
    :refresh_button => true,
    :pager          => true

  gridify :demo0302,
    :title          => I18n.t('txt.jqgrid.demo.20master'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :select_rows    => "javascript: handleDemo0302",
    :search_button  => true,
    :refresh_button => true,
    :pager          => true,
    :collapsible    => true

  gridify :demo0303,
    :title          => I18n.t('txt.jqgrid.demo.20subgrid'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :search_button  => true,
    :refresh_button => true,
    :pager          => true,
    :grid_view      => false,
    :sub_grid       => true,
    :sub_grid_url   => "/jqgrid/demo?model=invline&subgrid=true&atr[]=num&atr[]=item&atr[]=qty&atr[]=unit&atr[]=total",
    :sub_grid_model => [
                         {
                           :name  => [
                                       I18n.t('activerecord.attributes.invline.num'),
                                       I18n.t('activerecord.attributes.invline.item'),
                                       I18n.t('activerecord.attributes.invline.qty'),
                                       I18n.t('activerecord.attributes.invline.unit'),
                                       I18n.t('activerecord.attributes.invline.total')
                                     ],
                           :width => [ 55, 200, 80, 80, 80],
                           :align => [ :right, :left, :right, :right, :right ]
                         }
                       ]

  gridify :demo0304,
    :title          => I18n.t('txt.jqgrid.demo.20as_subgrid'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50,
                                        :align    => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :grid_view      => false,
    :search_button  => true,
    :refresh_button => true,
    :pager          => true

  gridify :demo0305,
    :title          => I18n.t('txt.jqgrid.demo.20resizing'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colInclude     => [:client],
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50,
                                        :align => :right },
                         :invdate  => { :name  => 'invdate',
                                        :width =>  90 },
                         :client_id => { :name  => 'client.name',
                                         :width => 100,
                                         :sortable => false },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => :right },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => :right },
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => :right },
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 500,
    :width_fit      => :fitted,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :jqgrid_options => { :viewsortcols => [true, :horizontal,false] },
    :search_button  => true,
    :refresh_button => true,
    :pager          => true
    
end
