class Invheader < ActiveRecord::Base
  belongs_to :client
  
  gridify :demo0101,
    :title          => I18n.t('txt.jqgrid.demo.xml_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :xml,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50, 
                                        :align => "right"  },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    #:include        => :client,
    :height         => :auto,
    :sort_by        => :id,
    :sort_order     => :desc,
    :rows_per_page  => 10,     
    :paging_choices => [10,20,30],  
    #:autowidth:     => true, 
    #:viewrecords    => true,    
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0102,
    :title          => I18n.t('txt.jqgrid.demo.json_data'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name  => 'id',
                                        :width =>  50, 
                                        :align => "right"  },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    #:include        => [:client],
    :height         => :auto,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo0103,
    :title          => I18n.t('txt.jqgrid.demo.once'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    
   # {name:'id',index:'id', width:60, sorttype:"int"},
   # {name:'invdate',index:'invdate', width:90, sorttype:"date"},
   # {name:'name',index:'name', width:100}, 
   # {name:'amount',index:'amount', width:80, align:"right",sorttype:"float"}, 
   # {name:'tax',index:'tax', width:80, align:"right",sorttype:"float"}, 
   # {name:'total',index:'total', width:80,align:"right",sorttype:"float"}, 
   # {name:'note',index:'note', width:150, sortable:false} 
    
    :height         => :auto,
    :rows_per_page  => 20,
    :paging_choices => [10,20,30],
    :pager          => true,
    :load_once      => true       
    
  gridify :demo1401,
    :title          => I18n.t('txt.jqgrid.demo.api'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 700,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true       
    
  gridify :demo1402,
    :title          => I18n.t('txt.jqgrid.demo.rtl'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    #:direction      => "rtl",
    #:recordpos      => "left", 
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true      
    
  gridify :demo1403,
    :title          => I18n.t('txt.jqgrid.demo.reordering'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :arranger       => :sortable,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo1404,
    :title          => I18n.t('txt.jqgrid.demo.chooser'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name  => 'amount',
                                        :width =>  80,
                                        :align => "right" },
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :arranger       => :chooser,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
    
  gridify :demo1405,
    :title          => I18n.t('txt.jqgrid.demo.validation'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right",
                                        :validations => { :custom => true , 
                                                          :custom_func => "javascript: mycheck" } },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true,  
    :editable       => true,
    :edit_button    => true,
    :add_button     => true, 
    :delete_button  => true
    
  gridify :demo1406,
    :title          => I18n.t('txt.jqgrid.demo.cinput'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100,                                         
                                        :edit_type    => :custom, 
                                        :edit_options => { :custom_element => "javascript: my_input",
                                                           :custom_value   => "javascript: my_value" } },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right" },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true,     
    :editable       => true,
    :inline_edit    => true,
    :add_button     => true, 
    :delete_button  => true
    
  gridify :demo1411,
    :title          => I18n.t('txt.jqgrid.demo.resizing'),
    :url            => "/jqgrid/demo",
    :data_type      => :json,
    :colNames       => [
                        I18n.t('activerecord.attributes.invheader.id'),
                        I18n.t('activerecord.attributes.invheader.invdate'),
                        I18n.t('activerecord.attributes.invheader.client'),
                        I18n.t('activerecord.attributes.invheader.amount'),
                        I18n.t('activerecord.attributes.invheader.tax'),
                        I18n.t('activerecord.attributes.invheader.total'),
                        I18n.t('activerecord.attributes.invheader.note'),
                        I18n.t('activerecord.attributes.invheader.closed'),
                        I18n.t('activerecord.attributes.invheader.ship_via')
                       ],
    :colModel       => {
                         :id       => { :name     => 'id',
                                        :width    =>  50, 
                                        :align    => "right" },
                         :invdate  => { :name  => 'invdate',  
                                        :width =>  90 },
                         :name     => { :name  => 'name',
                                        :width => 100 },
                         :amount   => { :name        => 'amount',
                                        :width       =>  80,
                                        :align       => "right" },  
                         :tax      => { :name  => 'tax',
                                        :width =>  80,
                                        :align => "right" },    
                         :total    => { :name  => 'total',
                                        :width =>  80,
                                        :align => "right" },   
                         :note     => { :name     => 'note',
                                        :width    => 150,
                                        :sortable => false },
                         :closed   => { :name  => 'closed',
                                        :width =>  40 },
                         :ship_via => { :name  => 'ship_via',
                                        :width =>  40 }
                       },
    :width          => 600,
    :width_fit      => :fitted,
    :height         => :auto,
    :rows_per_page  => 10,
    :paging_choices => [10,20,30],
    :sort_by        => :id,
    :sort_order     => :desc,
    :search_button  => true,  
    :refresh_button => true,
    :pager          => true
end

